# Generated by Django 6.0.4 on 2026-04-09 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('GR', 'Gramo'), ('LT', 'Litro'), ('ML', 'Mililitro'), ('UNIDAD', 'Unidad')], max_length=10)),
                ('stock_minimo', models.IntegerField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(choices=[('ALACENA', 'Alacena'), ('HELADERA', 'Heladera'), ('FREEZER', 'Freezer'), ('DESPENSA', 'Despensa')], max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
            ],
        ),
    ]
