# Generated by Django 6.0.4 on 2026-04-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(choices=[('ALACENA', 'Alacena'), ('HELADERA', 'Heladera'), ('FREEZER', 'Freezer'), ('DESPENSA', 'Despensa'), ('BAÑO', 'Baño')], max_length=10),
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.IntegerField()),
                ('comprado', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
